"""empty message

Revision ID: 81c4da38e881
Revises: 87500d52f43d
Create Date: 2025-09-04 16:00:39.658394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c4da38e881'
down_revision: Union[str, Sequence[str], None] = '87500d52f43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_confirmation_code', sa.String(), nullable=True))
    op.drop_column('users', 'phone_confirmation_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_confirmation_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'phone_confirmation_code')
    # ### end Alembic commands ###
